name: frc_tracker
description: A FIRST Robotics event tracking platform for mobile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  cached_network_image: ^3.2.3
  fl_chart: ^0.62.0
  flutter_html: ^3.0.0-beta.2
  intl: ^0.18.0
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700