include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_void_to_null
    - test_types_in_equals
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps

analyzer:
  errors:
    # Allow having TODOs in the code.
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"