name: flutter_frc_tracker
description: A FIRST Robotics Championship Tracker mobile app

# The following defines the version and build number for your application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  google_fonts: ^5.1.0
  fl_chart: ^0.63.0
  flutter_html: ^3.0.0-beta.2
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3

  # State Management
  provider: ^6.0.5
  flutter_riverpod: ^2.3.6

  # Networking & Data
  http: ^1.1.0
  dio: ^5.3.2
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.1.12
  path_provider: ^2.1.0
  logger: ^1.4.0
  connectivity_plus: ^4.0.2
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.2
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

# Flutter app configuration
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#3949AB"
  image: assets/images/splash_logo.png
  android: true
  ios: true